# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12MMJhA66Fc9dZ2g_Dyx2fgawDUse_6nG
"""

# Commented out IPython magic to ensure Python compatibility.
## download and connect to dataset
!pip install sqlalchemy==1.3.9

!pip install ipython-sql
!pip install ipython-sql prettytable

# %load_ext sql

import csv, sqlite3
import prettytable
prettytable.DEFAULT = 'DEFAULT'

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

!pip install -q pandas

# %sql sqlite:///my_data1.db

import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

#DROP THE TABLE IF EXISTS

# %sql DROP TABLE IF EXISTS SPACEXTABLE;

# %sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

## download and connect to dataset
!pip install sqlalchemy==1.3.9

!pip install ipython-sql
!pip install ipython-sql prettytable

# %load_ext sql

import csv, sqlite3
import prettytable
prettytable.DEFAULT = 'DEFAULT'

con = sqlite3.connect("my_data1.db")
cur = con.cursor()

!pip install -q pandas

# %sql sqlite:///my_data1.db

import pandas as pd
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv")
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")

#DROP THE TABLE IF EXISTS

# %sql DROP TABLE IF EXISTS SPACEXTABLE;

# %sql create table SPACEXTABLE as select * from SPACEXTBL where Date is not null

#Task 1
#Display the names of the unique launch sites in the space mission
# %sql SELECT DISTINCT Launch_Site FROM SPACEXTABLE;